
package consultoriodental;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JOptionPane;

/**
 *
 * @author Armando1
 */
public class AgregarPaciente extends javax.swing.JInternalFrame {
    soloPanel auxPanel;
    String url="jdbc:mysql://localhost:3306/clinicadental?user=root&password=panda101";
    /**
     * Creates new form AgregarPaciente
     */
    public AgregarPaciente() {
        initComponents();
            setTitle("AGREGAR NUEVO PACIENTE");
          FondoPanel fp  = new FondoPanel("/fondo/fondoverde.jpg");
        fp.setSize(794, 509);
        this.add(fp,BorderLayout.CENTER);
        this.pack();
    }
    private boolean locked = false;

    @Override
    public void reshape(int x, int y, int width, int height) {
        if (!locked) {
            super.reshape(x, y, width, height);
        }
    }

    public boolean isLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iHombre = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        iMujer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        iNombre = new javax.swing.JTextField();
        iApPat = new javax.swing.JTextField();
        iApMaterno = new javax.swing.JTextField();
        iCalle = new javax.swing.JTextField();
        iColonia = new javax.swing.JTextField();
        iMunicipio = new javax.swing.JTextField();
        iCodpost = new javax.swing.JTextField();
        iEmail = new javax.swing.JTextField();
        iContraseña = new javax.swing.JTextField();
        iTelefono = new javax.swing.JTextField();
        agregar1 = new javax.swing.JButton();
        agregar2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        iEstado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        otroCheck = new javax.swing.JCheckBox();
        cancer = new javax.swing.JCheckBox();
        respiratoria = new javax.swing.JCheckBox();
        cardiovascular = new javax.swing.JCheckBox();
        diabetes = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        otroC = new javax.swing.JCheckBox();
        animalesC = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        medicamentoCheck = new javax.swing.JCheckBox();
        materialC = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Email: ");

        jLabel9.setText("Fecha de \nNacimiento: ");

        jLabel11.setText("Contraseña: ");

        jLabel1.setText("Nombre(s)");

        jLabel2.setText("Apellido Paterno: ");

        jLabel13.setText("Municipio:");

        buttonGroup1.add(iHombre);
        iHombre.setSelected(true);
        iHombre.setText("Hombre");
        iHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iHombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido Materno: ");

        buttonGroup1.add(iMujer);
        iMujer.setText("Mujer");

        jLabel4.setText("Genero: ");

        jLabel5.setText("Calle y numero: ");

        jLabel6.setText("Colonia: ");

        jLabel7.setText("Codigo Postal: ");

        jLabel8.setText("Telefono: ");

        agregar1.setBackground(new java.awt.Color(168, 202, 235));
        agregar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agregar1.setText("Registrar");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });

        agregar2.setBackground(new java.awt.Color(168, 202, 235));
        agregar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agregar2.setText("Cancelar");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setMaxSelectableDate(new java.util.Date(1451631679000L));
        jDateChooser1.setMaximumSize(new java.awt.Dimension(21474836, 21474836));
        jDateChooser1.setMinSelectableDate(new java.util.Date(-631126740000L));

        jLabel12.setText("Estado:");

        otroCheck.setText("otro");
        otroCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otroCheckActionPerformed(evt);
            }
        });

        cancer.setText("Cáncer");

        respiratoria.setText("Respiratoria");

        cardiovascular.setText("Cardiovasculares");

        diabetes.setText("Diabetes");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Enfermedades crónicas");

        otroC.setText("otro");
        otroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otroCActionPerformed(evt);
            }
        });

        animalesC.setText("Animales");
        animalesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalesCActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Alergias");

        medicamentoCheck.setText("Medicamentos");
        medicamentoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoCheckActionPerformed(evt);
            }
        });

        materialC.setText("Material");
        materialC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(iApPat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(iApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iMujer)
                                    .addComponent(iHombre))
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(iMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iCodpost)
                                    .addComponent(iEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(agregar1)
                        .addGap(90, 90, 90)
                        .addComponent(agregar2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardiovascular)
                                    .addComponent(respiratoria)
                                    .addComponent(jLabel15)
                                    .addComponent(materialC)
                                    .addComponent(medicamentoCheck))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(otroCheck)
                                    .addComponent(diabetes)
                                    .addComponent(cancer)
                                    .addComponent(animalesC)
                                    .addComponent(otroC))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(iCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(iColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(iApPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel13)
                                            .addComponent(iApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(iCodpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(iEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(iEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(iContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(iHombre)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iMujer)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(iTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cardiovascular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(respiratoria))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(diabetes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otroCheck)))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(medicamentoCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(materialC))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(animalesC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(otroC)))))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar2)
                    .addComponent(agregar1))
                .addGap(49, 49, 49))
            .addComponent(jSeparator1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iHombreActionPerformed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection co = DriverManager.getConnection(url);
            Statement stm = co.createStatement();
            ResultSet rs = stm.executeQuery("select id_paciente from clinicadental.paciente where "
                    + "nombre='" + iNombre.getText() + "' and apellido_paterno='" + iApPat.getText() + "' and apellido_materno='" + iApMaterno.getText() + "'");

            String dat[] = new String[6];
            while (rs.next()) {                
                dat[0] = String.valueOf(rs.getString("id_paciente"));//id_paciente
            }
            
            if (dat[0] == null) {
                
                System.out.println("no se encontro, se procede a registrar");
                co = DriverManager.getConnection(url);
                    PreparedStatement pstm = co.prepareStatement("insert into clinicadental.paciente(nombre,apellido_paterno,apellido_materno,genero,calle_numero,colonia,codigo_postal,estado,telefono,fecha_nacimiento,email,contrasena) "
                            + "values(?,?,?,?,?,?,?,?,?,?,?,?)");

                    System.out.println("slol");

                    // java.util.Date f= iFechaNAc.getDate();
                    java.util.Date f = jDateChooser1.getDate();
                    java.sql.Date d = new java.sql.Date(f.getTime());
                    System.out.println("slol2");
                    pstm.setString(1, iNombre.getText());
                    pstm.setString(2, iApPat.getText());
                    pstm.setString(3, iApMaterno.getText());
                    pstm.setString(4, (iHombre.isSelected() ? "H" : "M"));
                    System.out.println("slol3");
                    pstm.setString(5, iCalle.getText());
                    pstm.setString(6, iColonia.getText());
                    pstm.setString(7, iCodpost.getText());
                    System.out.println("slol4");
                    pstm.setString(8, iEstado.getText());
                    pstm.setString(9, iTelefono.getText());
                    System.out.println("slol5");
                    pstm.setDate(10, d);
                    System.out.println("slol6");
                    pstm.setString(11, iEmail.getText());
                    pstm.setString(12, iContraseña.getText());
                    System.out.println("slol7");
                    pstm.executeUpdate();
                    System.out.println("se hizo");
                    
                    
                JOptionPane.showMessageDialog(rootPane, "EL PACIENTE SE REGISTRO CON EXITO ");
            }else{
                JOptionPane.showMessageDialog(rootPane, "EL PACIENTE YA SE ENCUENTRA REGISTRADO",null,JOptionPane.WARNING_MESSAGE);
            }
        } catch (ClassNotFoundException exc) {
            System.out.println(" no se hizo");
        } catch (SQLException ex) {
            //Logger.getLogger(ConexionSQL.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no se que onda");
        }
    }//GEN-LAST:event_agregar1ActionPerformed

    private void otroCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otroCheckActionPerformed

    }//GEN-LAST:event_otroCheckActionPerformed

    private void otroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otroCActionPerformed

    }//GEN-LAST:event_otroCActionPerformed

    private void animalesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalesCActionPerformed

    }//GEN-LAST:event_animalesCActionPerformed

    private void medicamentoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoCheckActionPerformed

    }//GEN-LAST:event_medicamentoCheckActionPerformed

    private void materialCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCActionPerformed

    }//GEN-LAST:event_materialCActionPerformed
    private void registrarSalir(java.awt.event.ActionEvent evt) {
        agregar1ActionPerformed(evt);
        auxPanel.morir();
        
    }
    public void panelPadre(soloPanel sp){
        auxPanel=sp;
    }
    
    //metodo que llama agregar_cita si es que el paciente no se encuentra registrado en el sistema
    public void asignarValor(String nom,String apP,String apM){
        iNombre.setText(nom);
        iApMaterno.setText(apM);
        iApPat.setText(apP);
        agregar1.removeActionListener(agregar1.getActionListeners()[0]);
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSalir(evt);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar1;
    private javax.swing.JButton agregar2;
    private javax.swing.JCheckBox animalesC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cancer;
    private javax.swing.JCheckBox cardiovascular;
    private javax.swing.JCheckBox diabetes;
    private javax.swing.JTextField iApMaterno;
    private javax.swing.JTextField iApPat;
    private javax.swing.JTextField iCalle;
    private javax.swing.JTextField iCodpost;
    private javax.swing.JTextField iColonia;
    private javax.swing.JTextField iContraseña;
    private javax.swing.JTextField iEmail;
    private javax.swing.JTextField iEstado;
    private javax.swing.JRadioButton iHombre;
    private javax.swing.JRadioButton iMujer;
    private javax.swing.JTextField iMunicipio;
    private javax.swing.JTextField iNombre;
    private javax.swing.JTextField iTelefono;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox materialC;
    private javax.swing.JCheckBox medicamentoCheck;
    private javax.swing.JCheckBox otroC;
    private javax.swing.JCheckBox otroCheck;
    private javax.swing.JCheckBox respiratoria;
    // End of variables declaration//GEN-END:variables
}
