/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultoriodental;

import java.awt.BorderLayout;
import java.io.IOException;
import java.net.Socket;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Armando1
 */
public class BuscarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCita
     */
    ArrayList<Object[]> datos;
    DefaultListModel model= new DefaultListModel();
    String url ="jdbc:mysql://localhost:3306/clinicadental?user=root&password=panda101";
    MenuPrincipal mp;
    MenuSecretaria ms;
    
    public BuscarCita(boolean permisos,JFrame menu) {
        initComponents();
        if(permisos){
            mp=(MenuPrincipal)menu;
        }else{
            ms=(MenuSecretaria)menu;
        }
           // Agregar_cita.ManejadorTecla mt = new Agregar_cita.ManejadorTecla();
        setTitle("Buscar Cita");
          FondoPanel fp  = new FondoPanel("/fondo/fondoverde.jpg");
        fp.setSize(794, 509);
        this.add(fp,BorderLayout.CENTER);
      //  this.setBounds(0, 0, 200, 200);
      this.setLocked(true);
      iBuscarFecha.setVisible(false);
      iBuscar.setToolTipText("ingrese nombre o algun apellido a filtrar");
      iBuscarFecha.setToolTipText("ingrese una fecha valida");
      model.add(0, "NOMBRE     APELLIDO PAT     APELLIDO MAT");
      listaFiltro.setModel(model);
      
      this.pack();
        
    }
    private boolean locked = false;

    @Override
    public void reshape(int x, int y, int width, int height) {
        if (!locked) {
            super.reshape(x, y, width, height);
        }
    }

    public boolean isLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }
    
    public void agregarDatosList(ArrayList<Object[]> datos){
        String aux="";
        for (int i=0;i<datos.size();i++) {
            aux=(String) datos.get(i)[0]+"          "+datos.get(i)[1]+"        "+datos.get(i)[2];
            model.addElement(aux);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seleccionarBusqueda = new javax.swing.JComboBox();
        bFiltrar = new javax.swing.JButton();
        iBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        oDetalles = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        iBuscarFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaFiltro = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        bCancelarCita = new javax.swing.JButton();
        bPosponerCita = new javax.swing.JButton();

        jLabel1.setText("Buscar por:");

        seleccionarBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fecha", "Nombre de Paciente" }));
        seleccionarBusqueda.setSelectedIndex(1);
        seleccionarBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seleccionarBusquedaItemStateChanged(evt);
            }
        });

        bFiltrar.setBackground(new java.awt.Color(168, 202, 235));
        bFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        oDetalles.setEditable(false);
        oDetalles.setColumns(20);
        oDetalles.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        oDetalles.setRows(5);
        jScrollPane2.setViewportView(oDetalles);

        jLabel2.setText("Coincidencias: ");

        iBuscarFecha.setDate(obtenerFechaActual());
        iBuscarFecha.setMaxSelectableDate(new java.util.Date(1546326115000L));
        iBuscarFecha.setMinSelectableDate(new java.util.Date(1420095715000L));

        listaFiltro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaFiltro.setToolTipText("selecione un nombre para ver mas detalles");
        listaFiltro.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaFiltroValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaFiltro);

        jLabel3.setText("Detalles busqueda:");

        bCancelarCita.setText("Cancelar Cita");
        bCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarCitaActionPerformed(evt);
            }
        });

        bPosponerCita.setText("Posponer Cita");
        bPosponerCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPosponerCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(seleccionarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bFiltrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bCancelarCita)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bPosponerCita))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(seleccionarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCancelarCita)
                            .addComponent(bPosponerCita)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(bFiltrar)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seleccionarBusquedaItemStateChanged
        if(seleccionarBusqueda.getSelectedIndex()==1){
            iBuscarFecha.setDate(null);
            iBuscar.setVisible(true);   
            iBuscarFecha.setVisible(false); 
        }else{
            iBuscar.setText("");
            iBuscarFecha.setVisible(true); 
            iBuscar.setVisible(false);            
        }
    }//GEN-LAST:event_seleccionarBusquedaItemStateChanged

    private void clearResult(){
        model.removeAllElements();
        model.add(0, "NOMBRE     APELLIDO PAT     APELLIDO MAT");
        oDetalles.setText("");
        listaFiltro.setSelectedIndex(0);  
    }
    
    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        if (!iBuscar.getText().isEmpty() || iBuscarFecha.getDate() != null) {
            datos = new ArrayList<>();
            clearResult();
            String buscarpor = "";
            SimpleDateFormat fecha = new SimpleDateFormat("dd-MM-yyyy");
            if (seleccionarBusqueda.getSelectedIndex() == 1) {
                buscarpor = "Select * from paciente p inner join cita c on p.id_paciente=c.id_paciente "
                        + "where p.nombre like '%" + iBuscar.getText() + "%' or apellido_Paterno like '%" + iBuscar.getText() + "%' or apellido_materno like '%" + iBuscar.getText() + "%'";
            } else {
                ///// METER UN IF PARA SOLO MOSTRAR CITAS FUTURAS NO PASADAS
                buscarpor = "Select * from paciente p inner join cita c on p.id_paciente=c.id_paciente"
                        + " where c.fecha_cita = '" + fecha.format(iBuscarFecha.getDate()) + "'";
            }
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection co = DriverManager.getConnection(url);

                Statement stm = co.createStatement();
                ResultSet rs = stm.executeQuery(buscarpor);

                
                boolean flag = false;
                    while (rs.next()) {
                    
                        String dat[] = new String[11];
                        dat[0] = String.valueOf(rs.getString("nombre"));//nombre
                        dat[1] = String.valueOf(rs.getString("apellido_Paterno"));//apPaterno
                        dat[2] = String.valueOf(rs.getString("apellido_materno"));//apMaterno 
                        dat[3] = String.valueOf(rs.getString("genero"));//id_paciente
                        dat[4] = String.valueOf(rs.getString("telefono"));//nombre
                        dat[5] = String.valueOf(rs.getString("fecha_cita"));//apPaterno
                        dat[6] = String.valueOf(rs.getString("hora_cita"));//apMaterno 
                        dat[7] = String.valueOf(rs.getString("motivo"));//apMaterno 

                        dat[8] = String.valueOf(rs.getString("id_cita"));//id_cita
                        dat[9] = String.valueOf(rs.getString("id_paciente"));//id_paciente
                        dat[11]= String.valueOf(rs.getString("email"));//id_paciente
                        datos.add(dat);
                        flag=true;
                    }
                    if(flag)
                    agregarDatosList(datos);                
                    else
                        JOptionPane.showMessageDialog(this, "No hay citas que coincidan con la busqueda");
                    rs.close();
                    co.close();
                        
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(BuscarCita.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"ingrese un valor para efectuar la busqueda");
        }
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void listaFiltroValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaFiltroValueChanged
        if (listaFiltro.getSelectedIndex() >0) {
            int auxindex = listaFiltro.getSelectedIndex() - 1;

            String datosss = "";
            datosss += "NOMBRE: " + datos.get(auxindex)[0] + "\n";
            datosss += "APELLIDO PATERNO: " + datos.get(auxindex)[1] + "\n";
            datosss += "APELLIDO MATERNO: " + datos.get(auxindex)[2] + "\n";
            datosss += "GENERO: " + datos.get(auxindex)[3] + "\n";
            datosss += "TELEFONO: " + datos.get(auxindex)[4] + "\n";
            datosss += "FECHA DE LA CITA: " + datos.get(auxindex)[5] + "\n";
            datosss += "HORA DE LA CITA: " + datos.get(auxindex)[6] + "\n";
            datosss += "MOTIVO DE LA CITA: " + datos.get(auxindex)[7];
            
            oDetalles.setText(datosss);

        }
    }//GEN-LAST:event_listaFiltroValueChanged

    private void EnviarMailConfirmacion(String to,String Men) {
        String para=to;
        String Mensage=Men;
        String Asunto="CITA AGENDADA EXITOSAMENTE";
        EnviarMail env = new EnviarMail(para, Mensage, Asunto);
        env.SendMail();        
    
    }
    private void bCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarCitaActionPerformed
        // TODO add your handling code here:
        if (listaFiltro.getSelectedIndex() > 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "¿Realmente desea cancelar la cita ?",
                    "Cancelacion de cita", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                bFiltrarActionPerformed(evt);
                int auxindex = listaFiltro.getSelectedIndex() - 1;
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection co = DriverManager.getConnection(url);
                    PreparedStatement stmt = co.prepareStatement("DELETE FROM cita WHERE id_cita=" + Integer.parseInt((String) datos.get(auxindex)[8]) + " and id_paciente =" + Integer.parseInt((String) datos.get(auxindex)[9]));
                    stmt.executeUpdate();
                    stmt.close();
                    co.close();
                    try {
                    Socket s = new Socket("www.gmail.com", 80);
                    if (s.isConnected()) {
                        String men="Querido usuario:  "+datos.get(listaFiltro.getSelectedIndex() - 1)[0]+" "+datos.get(listaFiltro.getSelectedIndex() - 1)[1]+" "+datos.get(listaFiltro.getSelectedIndex() - 1)[2]+
                                ".\nlamentamos informarle que su cita del dia: "+datos.get(auxindex)[5]+""
                    + "\n y hora: "+datos.get(auxindex)[6]+"a sido cancelada.\nGracias por su preferencia.";
                        EnviarMailConfirmacion((String) datos.get(auxindex)[11],men);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(AgregarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                    JOptionPane.showMessageDialog(this, "Cita Eliminada con exito");
                } catch (ClassNotFoundException exc) {
                    exc.printStackTrace();
                } catch (SQLException ex) {
                    Logger.getLogger(BuscarCita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bCancelarCitaActionPerformed

    private void bPosponerCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPosponerCitaActionPerformed
        // TODO add your handling code here:
        if (listaFiltro.getSelectedIndex() > 0) {
            System.out.println("posponer");
            int auxindex = listaFiltro.getSelectedIndex() - 1;
            PanelCalendarCita pc = new PanelCalendarCita(this, (String) datos.get(auxindex)[8]);
            JDialog frame = new JDialog();
            frame.add(pc);
            frame.setModal(true);
            System.out.println("posponer");
            frame.setLocationRelativeTo(this);
            
            frame.setVisible(true);
            pc.show();
            frame.setEnabled(true);
            frame.setFocusCycleRoot(true);
            
        }
    }//GEN-LAST:event_bPosponerCitaActionPerformed

    public void ActualizarCita(String id,String hora,Date dia){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection(url);
            PreparedStatement stmt = co.prepareStatement("UPDATE  cita SET fecha_cita=?,hora_cita=? where id_cita="+id);
            
            stmt.setDate(1, dia);
            stmt.setString(2, hora);
            
            stmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Cita Actualizada");
        }
        catch(ClassNotFoundException exc){
            exc.printStackTrace();
        }catch(SQLException ex){
            //Logger.getLogger(ConexionSQL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public java.util.Date obtenerFechaActual() {
        java.util.Date date = new java.util.Date();
        SimpleDateFormat fdate = new SimpleDateFormat("dd");
        SimpleDateFormat fMes = new SimpleDateFormat("MM");

        int dia = (Integer.parseInt(fdate.format(date)));
        int mes = (Integer.parseInt(fMes.format(date)));
        if (mes == 02) {
            if (dia < 28) {
                dia += 1;
            } else {
                dia = 1;
                mes += 1;
            }
        }
        if (mes == 01 && mes == 03 && mes == 05 && mes == 07 && mes == 8 && mes == 10 && mes == 12) {
            if (dia < 31) {
                dia += 1;
            } else {
                dia = 1;
                mes += 1;
            }
        } else if (dia < 30) {
            dia += 1;
        } else {
            dia = 1;
            mes += 1;
        }

        Calendar min = Calendar.getInstance();
        min.setTime(date);
        min.set(Calendar.MONTH, mes - 1);
        min.set(Calendar.DATE, dia);
        System.out.println("fecha actual : "+min.getTime().toString());
        return min.getTime();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarCita;
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bPosponerCita;
    private javax.swing.JTextField iBuscar;
    private com.toedter.calendar.JDateChooser iBuscarFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaFiltro;
    private javax.swing.JTextArea oDetalles;
    private javax.swing.JComboBox seleccionarBusqueda;
    // End of variables declaration//GEN-END:variables
}
