/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultoriodental;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JDialog;
/**
 *
 * @author yorch
 */
public class PanelCalendarCita extends javax.swing.JPanel {

    JDialog padre;
    int accion;
    /**
     * Creates new form PanelCalendarCita
     */
    BuscarCita bc;
    String id_cita;
    public PanelCalendarCita(BuscarCita b,String id) {
        bc=b;
        id_cita=id;
        initComponents();
        setVisible(true);
        revalidate();
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iHora = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iFecha = new com.toedter.calendar.JCalendar();

        iHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00" }));

        jLabel4.setText("Hora:");

        jButton1.setText("Reagendar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        iFecha.setMaxSelectableDate(new java.util.Date(1546326090000L));
        iFecha.setMinSelectableDate(obtenerFechaActual());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(iHora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.util.Date f = iFecha.getDate();
        bc.ActualizarCita(id_cita,iHora.getSelectedItem().toString() ,f,evt);
        System.out.println("panel calendarcita");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        accion=1;
        padre.setVisible(false);
        padre.setEnabled(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setPanelPadre(JDialog jp){
        padre=jp;
    }
   public java.util.Date obtenerFechaActual() {
        java.util.Date date = new java.util.Date();
        SimpleDateFormat fdate = new SimpleDateFormat("dd");
        SimpleDateFormat fMes = new SimpleDateFormat("MM");

        int dia = (Integer.parseInt(fdate.format(date)));
        int mes = (Integer.parseInt(fMes.format(date)));
        if (mes == 02) {
            if (dia < 28) {
                dia += 1;
            } else {
                dia = 1;
                mes += 1;
            }
        }
        if (mes == 01 && mes == 03 && mes == 05 && mes == 07 && mes == 8 && mes == 10 && mes == 12) {
            if (dia < 31) {
                dia += 1;
            } else {
                dia = 1;
                mes += 1;
            }
        } else if (dia < 30) {
            dia += 1;
        } else {
            dia = 1;
            mes += 1;
        }

        Calendar min = Calendar.getInstance();
        min.setTime(date);
        min.set(Calendar.MONTH, mes - 1);
        min.set(Calendar.DATE, dia);
        System.out.println("fecha actual : "+min.getTime().toString());
        return min.getTime();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar iFecha;
    private javax.swing.JComboBox<String> iHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
